# Site settings
name: Sharon Jerop Kipruto
title: Sharon Jerop Kipruto| Software Engineer, Infrastructure
description: Software engineer building distributed systems.
url: https://sjeropkipruto.github.io/
baseurl: ""
email: https://sjeropkipruto.github.io
cover: https://sjeropkipruto.github.io/img/og.png
logo: https://sjeropkipruto.github.io/img/emojis/technologist.png
# resume: https://sjeropkipruto.github.io/resume.pdf
social:
  - title: email
    url: mailto:jeropkipruto@gmail.com
  - title: twitter
    url: https://twitter.com/jeropkipruto
  - title: instagram
    url: https://instagram.com/jeropkipruto
  - title: codepen
    url: http://codepen.io/jeropkipruto
  - title: github
    url: https://github.com/sjeropkipruto
  - title: linkedin
    url: https://www.linkedin.com/in/jerop

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
